apiVersion: v1
kind: ConfigMap
metadata:
  name: buildmaterials-config
data:
  # PostgreSQL настройки
  POSTGRES_DB: "buildmat_db"
  POSTGRES_USER: "admin"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  
  # Redis настройки
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Django настройки
  DJANGO_SETTINGS_MODULE: "config.settings"
  PYTHONUNBUFFERED: "1"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,buildmaterials.local,django-service"
