apiVersion: v1
kind: Secret
metadata:
  name: buildmaterials-secrets
type: Opaque
stringData:
  # PostgreSQL пароль (в продакшене используйте более сложный пароль!)
  POSTGRES_PASSWORD: "SecureP@ssw0rd123"
  
  # Django secret key (в продакшене генерируйте случайную!)
  SECRET_KEY: "django-insecure-change-this-in-production-abc123xyz789"
