apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stroymaterials-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: stroymaterials.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  # В продакшене добавьте TLS конфигурацию
  # tls:
  # - hosts:
  #   - stroymaterials.local
  #   secretName: stroymaterials-tls
